
kind: Service
apiVersion: v1
metadata:
  name: blog-ui-service
spec:
  selector:
    app: blog-ui
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30082
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog-ui-deployment
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blog-ui
    spec:
      containers:
      - name: blog-ui
        image: asia.gcr.io/fe-tmaki/blog-kotlin-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: cloud
        - name: JAVA_OPTS
          value: "-Xmx304M -Xss1M -XX:MaxMetaspaceSize=145M -XX:ReservedCodeCacheSize=240M -XX:CompressedClassSpaceSize=24M -XX:MaxDirectMemorySize=10M -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1"
        - name: SECURITY_USER_NAME
          valueFrom:
            configMapKeyRef:
              name: blog-config
              key: ops-username
        - name: SECURITY_USER_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: blog-config
              key: ops-password
        - name: SECURITY_OAUTH2_CLIENT_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: blog-config
              key: github-oauth-client-id
        - name: SECURITY_OAUTH2_CLIENT_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: blog-config
              key: github-oauth-client-secret
        - name: VCAP_APPLICATION
          valueFrom:
            configMapKeyRef:
              name: blog-config
              key: vcap-application.json
        - name: VCAP_SERVICES
          valueFrom:
            configMapKeyRef:
              name: blog-config
              key: vcap-services.json
        resources:
          limits:
            memory: "1024Mi"
          requests:
            memory: "1024Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3